insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hovde', '105', 'Ранковце', 'MA', 12597);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Morning', '73598', 'Krasnodar', 'CN', 13744);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pierstorff', '2', 'Trinidad', 'NY', 13868);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Eastlawn', '307', 'Siewierz', 'VT', 14587);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Union', '095', 'San Jose', 'VT', 14451);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Red Cloud', '042', 'Gustavia', 'NY', 12794);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Anhalt', '04355', 'Areia Branca', 'CN', 13018);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('West', '80', 'Trai Ngau', 'NH', 13036);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Graedel', '01321', 'Bhokadoke', 'NJ', 13121);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Cardinal', '20397', 'Thanatpin', 'VT', 13496);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Loeprich', '4', 'Kiili', 'NJ', 13522);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Mockingbird', '58953', 'Aţ Ţaybah', 'NY', 12322);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Garrison', '64044', 'Strasbourg', 'VT', 14359);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Loftsgordon', '5535', 'Dzhebariki-Khaya', 'NJ', 14190);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Butternut', '73699', 'Vuzenica', 'CN', 12500);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kinsman', '693', 'Chotepe', 'NH', 12248);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Surrey', '7726', 'Caçapava do Sul', 'MA', 14901);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Crescent Oaks', '6725', 'Alcanhões', 'NY', 14143);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pearson', '80493', 'Angers', 'CN', 12611);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Village', '08', 'Chenqing', 'NJ', 13589);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Washington', '2134', 'Yunxian Chengguanzhen', 'NJ', 12637);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Mayfield', '13199', 'Limín Khersonísou', 'NJ', 14254);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Fulton', '26240', 'Erong', 'NH', 12546);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Drewry', '257', 'Huanchillas', 'NY', 13097);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Farmco', '22', 'Aş Şūrah aş Şaghīrah', 'CN', 14346);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kropf', '9', 'Nanqiu', 'NY', 13447);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Derek', '0189', 'Skaryszew', 'CN', 14525);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Trailsway', '1198', 'Manakara', 'NJ', 14945);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Maryland', '8348', 'Laojunmiao', 'NJ', 12285);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Commercial', '69294', 'Kawungsari', 'NH', 12669);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ridgeway', '3', 'Västerås', 'NH', 12467);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Prairie Rose', '8', 'Villazón', 'VT', 13771);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ridgeway', '4', 'Chigang', 'NY', 13553);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Village Green', '5', 'Gorodets', 'VT', 13638);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Nevada', '443', 'Anao', 'MA', 14073);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Eagan', '59426', 'Innoshima', 'NY', 13013);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Oneill', '1117', 'Itabaiana', 'VT', 13963);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hanover', '5579', 'Buynaksk', 'NH', 14650);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Golf', '9', 'Mogadishu', 'VT', 12354);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Village Green', '0650', 'Nangerang', 'NJ', 13401);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Schurz', '58414', 'Guanfang', 'NJ', 13712);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sloan', '805', 'Martigues', 'NH', 14208);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Merrick', '4', 'Huilong', 'NH', 12732);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Westend', '6278', 'Limmared', 'NY', 13235);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Village', '2', 'Anxiang', 'CN', 13089);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ruskin', '54910', 'Hongshi', 'MA', 12965);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ridgeway', '76220', 'Cabcaben', 'NJ', 14939);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pond', '8', 'Wellington', 'VT', 13771);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lakewood Gardens', '49738', 'Tanabe', 'CN', 14833);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Garrison', '14', 'Ngô Đồng', 'MA', 13181);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Calypso', '3', 'Sabunçu', 'NH', 13744);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Schurz', '87', 'Manuel Cavazos Lerma', 'NJ', 14488);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Buena Vista', '63849', 'Zhuyu', 'VT', 14943);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Texas', '125', 'Quebradas', 'CN', 14269);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Magdeline', '934', 'Breia', 'CN', 14567);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hazelcrest', '16184', 'Indianapolis', 'NY', 12544);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Loomis', '68103', 'Madrid', 'CN', 13049);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Farwell', '67660', 'Usa River', 'CN', 12710);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Vernon', '195', 'Matou', 'NJ', 12660);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lukken', '8218', 'Dianbu', 'MA', 12122);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bluestem', '42', 'Majiang', 'NJ', 14389);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('1st', '30473', 'Jihuluntu Sumu', 'NJ', 13624);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Havey', '1', 'Iizuka', 'NJ', 12539);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Barnett', '88', 'Loma Bonita', 'MA', 12960);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Quincy', '0', 'Vegachí', 'NJ', 13006);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hagan', '53', 'Saint-Pierre', 'NH', 13977);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Springs', '0693', 'Nîmes', 'VT', 14090);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Maryland', '72335', 'Nová Cerekev', 'NY', 12159);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Walton', '5551', 'Baozhu', 'VT', 12271);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pleasure', '91116', 'Vila Chã de Ourique', 'NH', 14745);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Buena Vista', '5', 'Hua Hin', 'VT', 14538);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Veith', '056', 'Chuhuyiv', 'CN', 13944);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Blue Bill Park', '927', 'Jinggongqiao', 'VT', 12924);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hooker', '698', 'Saint Petersburg', 'NH', 13516);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Goodland', '3572', 'Marseille', 'MA', 14794);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Becker', '97228', 'Yixin', 'VT', 12521);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Schiller', '26011', 'Novovorontsovka', 'NH', 14134);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Moulton', '05601', 'Lesozavodsk', 'MA', 13852);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kinsman', '99657', 'Benito Juarez', 'MA', 12968);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lillian', '49468', 'Medveđa', 'VT', 14757);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Dryden', '6060', 'Farroupilha', 'CN', 12522);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Quincy', '443', 'Apoya', 'CN', 12479);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Crownhardt', '3', 'Horodok', 'MA', 13888);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Dahle', '9', 'San Cristóbal', 'MA', 13962);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Tennessee', '3731', 'Platagata', 'NH', 14816);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Elmside', '328', 'Ždánice', 'NJ', 14176);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Blackbird', '98', 'Napel', 'NJ', 13650);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Calypso', '88', 'Akkol’', 'CN', 12975);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Iowa', '89', 'Sadowie', 'VT', 13432);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Nelson', '4', 'Panggung', 'NJ', 14664);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ridge Oak', '88032', 'Novoaleksandrovsk', 'NJ', 14765);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Northport', '565', 'Otorohanga', 'NH', 13735);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Raven', '70', 'Canomoy', 'NY', 12221);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kipling', '18', 'Xiaojinkou', 'NY', 14009);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Waubesa', '8969', 'Jintan', 'NJ', 12848);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lunder', '9941', 'Jubung', 'CN', 13423);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Donald', '1', 'Bei’an', 'MA', 13354);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Merry', '64', 'Jepuro', 'NH', 13967);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bowman', '535', 'Athmuqam', 'VT', 12270);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Iowa', '1', 'Mirzāpur', 'MA', 13480);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bluestem', '85', 'Arrifes', 'NY', 14609);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Gulseth', '65', 'Al Wardānīn', 'CN', 14644);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ryan', '2085', 'Portela', 'NJ', 14771);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Valley Edge', '18', 'Qiankeng', 'MA', 13899);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sutteridge', '72', 'Chavárion', 'NJ', 12685);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Burning Wood', '037', 'Quebradas', 'MA', 14479);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Maywood', '33', 'Prang Ku', 'NJ', 13147);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Holy Cross', '76742', 'Lukou', 'VT', 12390);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Truax', '90', 'Sundsvall', 'CN', 14856);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Goodland', '29', 'Caleufú', 'NJ', 13692);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Quincy', '59', 'Tarnowiec', 'VT', 13129);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Crownhardt', '59530', 'Nggesa', 'CN', 12385);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Schurz', '9', 'Portela', 'VT', 14434);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Cascade', '7516', 'Sandaogou', 'NJ', 13635);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Parkside', '314', 'Jiufang', 'CN', 13546);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Spaight', '67', 'Khotiv', 'MA', 14193);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Rieder', '30307', 'Sibanicú', 'MA', 13646);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Dovetail', '002', 'Porto Feliz', 'MA', 14485);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bayside', '845', 'Bergen', 'CN', 13912);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Jenifer', '511', 'Caen', 'MA', 13691);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hansons', '9', 'Finiq', 'VT', 14042);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bartelt', '9550', 'Shubenka', 'NJ', 12402);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Darwin', '7961', 'Ōkawara', 'CN', 13025);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Gulseth', '9', 'Filótion', 'CN', 13868);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Johnson', '4123', 'Cafayate', 'NY', 14265);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Roth', '3', 'Kuching', 'NY', 14287);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Corscot', '0627', 'Zhuping', 'NH', 12145);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Fisk', '448', 'Kitapak', 'VT', 13051);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Little Fleur', '66', 'Pouso Alegre', 'NH', 12837);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Elka', '76955', 'Lykóvrysi', 'NH', 12212);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sugar', '488', 'Al Mazzūnah', 'NH', 13009);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Grover', '8887', 'Sasovo', 'CN', 14750);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Superior', '4', 'Rosebank', 'VT', 14893);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lyons', '5674', 'Maţāy', 'NJ', 14217);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bartillon', '50578', 'Langxi', 'CN', 12650);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Scofield', '4', 'Longmen', 'NY', 13953);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Onsgard', '99', 'Kaffrine', 'VT', 14383);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Thompson', '059', 'Susuman', 'NH', 12674);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Westend', '7645', 'Goshogawara', 'VT', 12462);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ruskin', '0028', 'Xingguo', 'CN', 14492);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Fuller', '8', 'Capatárida', 'NJ', 12415);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Prentice', '68955', 'Konduga', 'NJ', 14312);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Northfield', '05975', 'Pingdingshan', 'MA', 12125);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Doe Crossing', '21568', 'Bucaramanga', 'MA', 13472);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Annamark', '2989', 'Knežica', 'NJ', 13044);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Graedel', '56091', 'Beixin', 'NY', 13520);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Luster', '2159', 'Phoenix', 'VT', 14839);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Eastlawn', '53070', 'Priyutovo', 'NH', 14885);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Melrose', '85', 'Phôngsali', 'NJ', 14397);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Burning Wood', '5', 'Biasong', 'CN', 12709);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Village', '32', 'Kabac', 'CN', 14451);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Porter', '954', 'Aras-asan', 'NH', 12990);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Summerview', '32971', 'Guolemude', 'NY', 13152);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sauthoff', '8', 'Baitu', 'MA', 13236);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('International', '4254', 'Synya', 'CN', 13265);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Reinke', '56', 'Gonghe', 'MA', 14222);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Corben', '9', 'Qimantage', 'NY', 14170);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Brown', '02', 'Butigui', 'NY', 12789);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('David', '1432', 'Fuding', 'MA', 14511);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lyons', '513', 'Matsubara', 'VT', 12439);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Surrey', '8', 'Nairobi', 'NJ', 13157);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Scoville', '33', 'Majan', 'VT', 14849);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Hoepker', '7', 'Shenjing', 'NH', 13928);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Manitowish', '35354', 'Rifu', 'VT', 14068);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Holy Cross', '05528', 'Petrov', 'NJ', 12576);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Rockefeller', '1338', 'Thomassique', 'NJ', 14900);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('7th', '92676', 'Lau', 'NH', 13051);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Summerview', '5', 'Bang Racham', 'NH', 14017);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Corry', '2046', 'Matsubara', 'MA', 12689);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bunting', '6', 'Zbąszynek', 'NJ', 12619);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Morning', '76', 'Dartang', 'NH', 14561);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Killdeer', '26726', 'Cassanayan', 'NH', 14476);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Northwestern', '0', 'Toyoshina', 'MA', 13675);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Red Cloud', '6', 'Akureyri', 'NJ', 14241);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Center', '9', 'Ljubešćica', 'NH', 13868);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Eastlawn', '307', 'Daga', 'NH', 12922);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Green', '0888', 'Kardítsa', 'MA', 14364);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Continental', '3077', 'Muaraenim', 'VT', 14472);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Eagan', '4', 'Obispos', 'NY', 14448);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Amoth', '70', 'Gatesville', 'VT', 13476);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Arrowood', '5677', 'Kunheda Woerzu Manzu', 'MA', 12297);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pierstorff', '8', 'Vadstena', 'VT', 13020);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Garrison', '410', 'Lyubotyn', 'NJ', 12622);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ilene', '93727', 'Mizur', 'NH', 12782);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Scofield', '62', 'Grekan', 'VT', 12536);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Manufacturers', '1179', 'Kavýli', 'NY', 12533);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Colorado', '23', 'Xieyang', 'CN', 13737);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Superior', '2', 'La Valette-du-Var', 'VT', 14792);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kim', '74', 'Anyang-si', 'VT', 12827);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ramsey', '609', 'Gemena', 'NH', 14311);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Buena Vista', '6', 'Isperikh', 'VT', 13741);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kipling', '0', 'Mielec', 'NY', 13123);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Union', '8', 'Trairi', 'VT', 13869);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Center', '0', 'Tingqian', 'NJ', 13048);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Straubel', '3', 'Langchuan', 'NH', 13117);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ludington', '0', 'Sepit', 'CN', 13913);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Crownhardt', '118', 'Koni-Djodjo', 'NH', 12187);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sauthoff', '263', 'Aragua de Barcelona', 'MA', 14976);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Sutherland', '9', 'Totora', 'NJ', 14762);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Golden Leaf', '466', 'Bhunya', 'CN', 14745);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Marquette', '8862', 'Bairro', 'VT', 13236);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Green Ridge', '7', 'Tarakaniv', 'NY', 12189);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Birchwood', '259', 'Lima Pampa', 'MA', 14737);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Randy', '7068', 'Ollachea', 'NJ', 14254);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Northport', '3720', 'Gobernador Ingeniero Valentín Virasoro', 'NJ', 14677);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Elmside', '90311', 'Tokarnia', 'NJ', 12663);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pine View', '769', 'Kohlu', 'VT', 13812);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kinsman', '9', 'Klatakan', 'NH', 12170);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Corry', '58573', 'Al Manqaf', 'CN', 14547);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Prairieview', '4', 'Arroyo Seco', 'CN', 12742);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Parkside', '5406', 'Kingston', 'VT', 14296);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('American Ash', '72', 'Bayart Huxu', 'NH', 14966);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Saint Paul', '19', 'Camasca', 'CN', 12691);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Warner', '39495', 'Songgui', 'NY', 12504);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Rigney', '4', 'Jincheng', 'NJ', 14070);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Namekagon', '27', 'Água Levada', 'MA', 12304);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Paget', '693', 'Sandaoba', 'NH', 12795);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Brentwood', '528', 'Condado', 'NJ', 14772);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Meadow Vale', '1', 'La Uvita', 'NY', 12202);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Twin Pines', '8646', 'Qixian', 'NJ', 13708);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bluestem', '58188', 'Pamedilan', 'NJ', 14544);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Elgar', '754', 'Arazane', 'NH', 14349);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Coolidge', '8', 'Bałtów', 'NY', 13485);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bobwhite', '672', 'Stockholm', 'VT', 13188);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Park Meadow', '80', 'Monroe', 'CN', 12801);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Shopko', '7375', 'Cibebek', 'VT', 12515);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Elka', '94439', 'Malveira', 'MA', 12862);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Gina', '89474', 'Kumla', 'NH', 14085);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Debs', '556', 'Kaoma', 'CN', 12379);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Milwaukee', '9', 'Tras Cerros', 'MA', 14303);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Bonner', '502', 'Axioúpoli', 'CN', 14494);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Packers', '20420', 'Caloue', 'NY', 13531);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Longview', '1', 'Lazaro Cardenas', 'NH', 14362);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Reinke', '1556', 'Pyu', 'VT', 12547);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Pine View', '62199', 'Železnice', 'MA', 14798);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Annamark', '76950', 'Zhongxinqiao', 'NJ', 12380);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Westridge', '7', 'Xiejiatan', 'NJ', 14955);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Oneill', '9', 'Melchor de Mencos', 'NY', 14112);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Melby', '7507', 'Duri', 'VT', 14307);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Summer Ridge', '3', 'Jakubów', 'NH', 14962);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Lyons', '1', 'Olympia', 'CN', 13614);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Nevada', '069', 'Chitungwiza', 'MA', 14537);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('American', '54', 'Dofa', 'MA', 13414);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Milwaukee', '64528', 'Noginsk-9', 'NH', 13767);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Oxford', '54', 'Cusapín', 'NY', 12768);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Novick', '1503', 'Geyuan', 'VT', 12335);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Ridgeway', '190', 'Tatarsk', 'CN', 12404);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Kedzie', '73', 'Castlebridge', 'NY', 14509);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Green Ridge', '2781', 'Ḩarf al Musaytirah', 'CN', 13284);
insert into location (LOC_STNAME, LOC_STNUM, LOC_CITY, LOC_STATE, LOC_ZIP) values ('Westridge', '23', 'Gongju', 'MA', 12248);
