SELECT C.CUST_FNAME, C.CUST_LNAME, A.LOC_STATE AS 'STATE', INV_PRICE AS 'List',D.DEAL_NAME AS 'DEALERSHIP', L.LINE_PRICE AS 'SALE PRICE'
FROM CUSTOMER AS C
JOIN INVENTORY AS I ON C.VEH_NUM = I.VEH_NUM
JOIN LINE AS L ON I.INV_NUM = L.INV_NUM
JOIN SALES AS S ON S.CUST_NUM = C.CUST_NUM
JOIN dealership AS D ON D.DEAL_NUM = S.DEAL_NUM
JOIN employee AS E ON E.EMP_NUM = S.EMP_NUM
JOIN location AS A ON A.LOC_NUM = D.LOC_NUM
;